import Navbar from '@/components/Navbar';
import AppFooter from '@/components/AppFooter';
import SEO from '@/components/SEO';
import { FileText, Brain, CheckCircle, TrendingUp, Sparkles, Upload, MessageCircle, BarChart3, Zap, Layers, BookMarked, ArrowRight } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Link } from 'wouter';
import { Card, CardContent } from '@/components/ui/card';
import { motion } from 'framer-motion';
import { useLanguage } from '@/lib/i18n/LanguageContext';

export default function Features() {
  const { t, language } = useLanguage();

  const featureIcons = [FileText, Brain, Upload, CheckCircle, Layers, BookMarked, MessageCircle, Sparkles, TrendingUp, BarChart3];
  const featureGradients = [
    'from-blue-500/10 to-cyan-500/10', 'from-purple-500/10 to-pink-500/10',
    'from-emerald-500/10 to-teal-500/10', 'from-amber-500/10 to-orange-500/10',
    'from-green-500/10 to-emerald-500/10', 'from-rose-500/10 to-red-500/10',
    'from-indigo-500/10 to-violet-500/10', 'from-cyan-500/10 to-blue-500/10',
    'from-orange-500/10 to-amber-500/10', 'from-violet-500/10 to-purple-500/10',
  ];
  const featureColors = [
    'text-blue-500', 'text-purple-500', 'text-emerald-500', 'text-amber-500',
    'text-green-500', 'text-rose-500', 'text-indigo-500', 'text-cyan-500',
    'text-orange-500', 'text-violet-500',
  ];

  const allFeatureKeys = ['notes', 'summaries', 'upload', 'quiz', 'tariq', 'evaluation', 'tracking', 'advancedStats', 'revision'] as const;
  
  const newFeatures = language === 'fr' ? [
    {
      title: "Flashcards IA",
      description: "Générez automatiquement des flashcards depuis vos cours pour une révision active et efficace.",
      details: [
        "10-15 cartes par set générées par l'IA",
        "Animation de retournement fluide",
        "Suivi de maîtrise: Je sais / À revoir",
        "Barre de progression visuelle",
      ],
    },
    {
      title: "Guide d'Étude IA",
      description: "Obtenez des guides de révision structurés et personnalisés pour chaque cours.",
      details: [
        "Objectifs d'apprentissage clairs",
        "Concepts clés identifiés",
        "Pièges courants à éviter",
        "Exercices pratiques suggérés",
      ],
    },
  ] : [
    {
      title: "AI Flashcards",
      description: "Automatically generate flashcards from your courses for active and effective review.",
      details: [
        "10-15 cards per set generated by AI",
        "Smooth flip animation",
        "Mastery tracking: I know / To review",
        "Visual progress bar",
      ],
    },
    {
      title: "AI Study Guide",
      description: "Get structured, personalized study guides for each course.",
      details: [
        "Clear learning objectives",
        "Key concepts identified",
        "Common pitfalls to avoid",
        "Suggested practice exercises",
      ],
    },
  ];

  const baseFeatures = allFeatureKeys.map((key, index) => ({
    icon: featureIcons[index],
    gradient: featureGradients[index],
    iconColor: featureColors[index],
    title: t.featuresPage.features[key].title,
    description: t.featuresPage.features[key].description,
    details: t.featuresPage.features[key].details,
  }));

  const insertIndex = 4;
  const features = [
    ...baseFeatures.slice(0, insertIndex),
    {
      icon: Layers,
      gradient: featureGradients[4],
      iconColor: featureColors[4],
      title: newFeatures[0].title,
      description: newFeatures[0].description,
      details: newFeatures[0].details,
    },
    {
      icon: BookMarked,
      gradient: featureGradients[5],
      iconColor: featureColors[5],
      title: newFeatures[1].title,
      description: newFeatures[1].description,
      details: newFeatures[1].details,
    },
    ...baseFeatures.slice(insertIndex),
  ];

  const containerVariants = {
    hidden: { opacity: 0 },
    visible: {
      opacity: 1,
      transition: { staggerChildren: 0.06 },
    },
  };

  const itemVariants = {
    hidden: { y: 30, opacity: 0 },
    visible: {
      y: 0,
      opacity: 1,
      transition: { duration: 0.6, ease: [0.22, 1, 0.36, 1] },
    },
  };

  return (
    <div className="min-h-screen flex flex-col">
      <SEO 
        title={t.featuresPage.heroTitle}
        description={t.featuresPage.heroSubtitle}
        url="https://corrigetescours.com/features"
      />
      <Navbar />

      <main className="flex-1">
        <section className="relative py-20 md:py-32 px-4 sm:px-6 lg:px-8 overflow-hidden">
          <div className="absolute inset-0 bg-gradient-to-br from-primary/8 via-background to-purple-500/5 dark:from-primary/15 dark:via-background dark:to-purple-500/10" />
          <div className="absolute inset-0 bg-[radial-gradient(ellipse_80%_50%_at_50%_-20%,rgba(59,130,246,0.12),transparent)] dark:bg-[radial-gradient(ellipse_80%_50%_at_50%_-20%,rgba(59,130,246,0.2),transparent)]" />
          
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.8 }}
            className="max-w-4xl mx-auto text-center relative z-10"
          >
            <Badge variant="secondary" className="mb-6">
              <Zap className="w-3 h-3 mr-1" />
              {t.featuresPage.badge}
            </Badge>
            
            <h1 className="text-4xl md:text-5xl lg:text-6xl font-bold mb-6 leading-tight" data-testid="text-features-hero-title">
              {t.featuresPage.heroTitle}
            </h1>
            <p className="text-xl text-muted-foreground max-w-2xl mx-auto leading-relaxed">
              {t.featuresPage.heroSubtitle}
            </p>
          </motion.div>
        </section>

        <section className="py-20 md:py-28 px-4 sm:px-6 lg:px-8">
          <div className="max-w-7xl mx-auto">
            <motion.div
              variants={containerVariants}
              initial="hidden"
              whileInView="visible"
              viewport={{ once: true, margin: "-50px" }}
              className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6"
            >
              {features.map((feature, index) => (
                <motion.div key={index} variants={itemVariants}>
                  <Card className="h-full hover-elevate" data-testid={`card-feature-${index}`}>
                    <CardContent className="p-6">
                      <div className={`h-12 w-12 rounded-xl flex items-center justify-center mb-4 bg-gradient-to-br ${feature.gradient}`}>
                        <feature.icon className={`h-6 w-6 ${feature.iconColor}`} />
                      </div>
                      <h3 className="text-lg font-semibold mb-2">{feature.title}</h3>
                      <p className="text-sm text-muted-foreground mb-4 leading-relaxed">{feature.description}</p>
                      <ul className="space-y-2">
                        {feature.details.map((detail, idx) => (
                          <li key={idx} className="flex items-start gap-2 text-sm">
                            <CheckCircle className="h-4 w-4 text-primary mt-0.5 flex-shrink-0" />
                            <span className="text-muted-foreground">{detail}</span>
                          </li>
                        ))}
                      </ul>
                    </CardContent>
                  </Card>
                </motion.div>
              ))}
            </motion.div>
          </div>
        </section>

        <section className="py-20 md:py-28 px-4 sm:px-6 lg:px-8">
          <div className="max-w-5xl mx-auto">
            <div className="relative overflow-hidden rounded-2xl">
              <div className="absolute inset-0 bg-gradient-to-br from-primary via-primary to-purple-600" />
              <div className="absolute inset-0 bg-[radial-gradient(ellipse_at_top_right,rgba(255,255,255,0.15),transparent)]" />
              <div className="relative p-8 md:p-12 lg:p-16 text-center text-white">
                <h2 className="text-3xl md:text-4xl font-bold mb-4">
                  {t.featuresPage.ctaTitle}
                </h2>
                <p className="text-white/80 mb-8 text-lg max-w-2xl mx-auto leading-relaxed">
                  {t.featuresPage.ctaSubtitle}
                </p>
                <Link href="/signup">
                  <Button size="lg" variant="secondary" className="group" data-testid="button-signup-cta">
                    {t.featuresPage.ctaButton}
                    <ArrowRight className="w-4 h-4 ml-2 group-hover:translate-x-1 transition-transform" />
                  </Button>
                </Link>
              </div>
            </div>
          </div>
        </section>
      </main>

      <AppFooter />
    </div>
  );
}
